Repository ToGatherThem/gatherthem_server, pull requests merged in 2022-06, with the labels that each got.

#38 Feature/images
  src/main/java/fr/gatherthem/gatherthem_server/collections/domain/model/CollectionCreationModel.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/domain/model/CollectionModel.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/domain/model/ItemModel.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/domain/service/CollectionService.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/controller/CollectionController.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/dto/CollectionCreationDto.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/dto/CollectionDto.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/dto/CollectionUpdateDto.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/dto/ItemCreationDto.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/dto/ItemDto.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/mapper/CollectionMapper.java
  src/main/java/fr/gatherthem/gatherthem_server/collections/mapper/ItemMapper.java
  src/main/java/fr/gatherthem/gatherthem_server/commons/entity/CollectionEntity.java
  src/main/java/fr/gatherthem/gatherthem_server/commons/entity/ItemEntity.java
  src/main/resources/sql/createTable.sql
Labels: enhancement

#45 [ADD] Edit profile
  src/main/java/fr/gatherthem/gatherthem_server/user/domain/model/UserUpdateModel.java
  src/main/java/fr/gatherthem/gatherthem_server/user/domain/service/UserService.java
  src/main/java/fr/gatherthem/gatherthem_server/user/exception/CurrentPasswordIncorrectException.java
  src/main/java/fr/gatherthem/gatherthem_server/user/exposition/controller/UserController.java
  src/main/java/fr/gatherthem/gatherthem_server/user/exposition/dto/UserUpdateDto.java
  src/main/java/fr/gatherthem/gatherthem_server/user/infrastructure/repository/UserRepository.java
  src/main/java/fr/gatherthem/gatherthem_server/user/mapper/UserMapper.java
  src/main/java/fr/gatherthem/gatherthem_server/user/mapper/UserUpdateMapper.java
  src/main/resources/openapi.yml
Labels: enhancement

#46 [ADD] Logout route
  src/main/java/fr/gatherthem/gatherthem_server/user/exposition/controller/UserController.java
  src/main/resources/openapi.yml
Labels: enhancement

#48 [ADD] Document controller routes
  src/main/java/fr/gatherthem/gatherthem_server/collections/exposition/controller/CollectionController.java
  src/main/java/fr/gatherthem/gatherthem_server/items/exposition/controller/ItemController.java
  src/main/java/fr/gatherthem/gatherthem_server/template/exposition/controller/TemplateController.java
  src/main/java/fr/gatherthem/gatherthem_server/user/exposition/controller/UserController.java
Labels: documentation

#50 [ADD] Profile image
  src/main/java/fr/gatherthem/gatherthem_server/commons/entity/UserEntity.java
  src/main/java/fr/gatherthem/gatherthem_server/user/domain/AppUser.java
  src/main/java/fr/gatherthem/gatherthem_server/user/domain/model/UserModel.java
  src/main/java/fr/gatherthem/gatherthem_server/user/domain/model/UserUpdateModel.java
  src/main/java/fr/gatherthem/gatherthem_server/user/domain/service/UserService.java
  src/main/java/fr/gatherthem/gatherthem_server/user/exposition/dto/UserDto.java
  src/main/java/fr/gatherthem/gatherthem_server/user/exposition/dto/UserUpdateDto.java
  src/main/java/fr/gatherthem/gatherthem_server/user/mapper/UserMapper.java
  src/main/java/fr/gatherthem/gatherthem_server/user/mapper/UserUpdateMapper.java
  src/main/resources/sql/createTable.sql
Labels: enhancement

#51 [FIX] fixing item update
  src/main/java/fr/gatherthem/gatherthem_server/items/domain/model/ItemPropertyUpdateModel.java
  src/main/java/fr/gatherthem/gatherthem_server/items/domain/service/ItemService.java
  src/main/java/fr/gatherthem/gatherthem_server/items/exposition/dto/ItemPropertyUpdateDto.java
  src/main/java/fr/gatherthem/gatherthem_server/items/infrastructure/repository/ItemRepository.java
  src/main/java/fr/gatherthem/gatherthem_server/items/mapper/ItemPropertyMapper.java
Labels: bug
